"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from "./components/navbar";
import { SessionProvider } from "next-auth/react"
import Footer from "./components/footer";
import store from "./store/store";
import { Provider } from "react-redux";
import AuthProvider from "./utils/SessionProvider";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"></link>
      {/* <SessionProvider session={session}> */}
      <AuthProvider>
      <Provider store={store}>
      <Navbar />
      {children}
      <Footer/>
      </Provider>
      </AuthProvider>
      {/* </SessionProvider> */}
      {/* </SessionProvider> */}
      </body>
    </html>
  );
}
